production:
    image: golang
    stage: deploy
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - go build -o main main.go 
        - scp main ubuntu@$DEPLOY_SERVER:/home/ubuntu
        #- scp creds.json ubuntu@$DEPLOY_SERVER:/home/ubuntu
    environment:
        name: production
